version: "3.1"
services:
  # MongoDB Database
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: rachidamrani
      MONGO_INITDB_ROOT_PASSWORD: pass123

  # Mongo Express:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rachidamrani
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - "mongodb"
